# Generated by Django 2.2.4 on 2020-04-02 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryShelves', '0003_auto_20200402_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='translator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='book', to='LibraryShelves.Translator'),
        ),
    ]
