# Generated by Django 2.2.4 on 2020-04-05 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryShelves', '0004_auto_20200402_1235'),
    ]

    operations = [
        migrations.CreateModel(
            name='Editor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('middle_name', models.CharField(blank=True, max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='cover',
            field=models.FileField(default='none', upload_to='book_covers/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='pub_year',
            field=models.CharField(default='none', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.CharField(default='none', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='subtitle',
            field=models.CharField(default='none', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='translator',
            name='middle_name',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='book',
            name='editor',
            field=models.ManyToManyField(related_name='book', to='LibraryShelves.Editor'),
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.ManyToManyField(related_name='book', to='LibraryShelves.Genre'),
        ),
    ]
