# Generated by Django 2.2.4 on 2020-04-05 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryShelves', '0005_auto_20200405_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.FileField(blank=True, upload_to='book_covers/'),
        ),
        migrations.AlterField(
            model_name='book',
            name='editor',
            field=models.ManyToManyField(blank=True, related_name='book', to='LibraryShelves.Editor'),
        ),
        migrations.AlterField(
            model_name='book',
            name='subtitle',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
