# Generated by Django 2.2.4 on 2020-04-07 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryShelves', '0006_auto_20200405_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.ImageField(blank=True, height_field=240, upload_to='book_covers/', width_field=240),
        ),
    ]
