# Generated by Django 2.2.4 on 2020-04-24 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryShelves', '0007_auto_20200406_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='published_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.FileField(blank=True, upload_to='book_covers/'),
        ),
    ]
