# Generated by Django 2.2.4 on 2020-04-27 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryShelves', '0008_auto_20200424_1431'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='translator',
        ),
        migrations.AddField(
            model_name='book',
            name='translator',
            field=models.ManyToManyField(blank=True, related_name='book', to='LibraryShelves.Translator'),
        ),
    ]
