# Generated by Django 2.2.4 on 2020-04-27 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryShelves', '0009_auto_20200427_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_format',
            field=models.CharField(blank=True, choices=[('PB', 'Paperback'), ('HC', 'Hardcover')], default='PB', max_length=2),
        ),
        migrations.AddField(
            model_name='book',
            name='pages',
            field=models.CharField(blank=True, max_length=10, verbose_name='Pages'),
        ),
        migrations.AddField(
            model_name='book',
            name='status',
            field=models.CharField(blank=True, choices=[('m', 'Maintenance'), ('o', 'On loan'), ('a', 'Available'), ('r', 'Reserved')], default='m', help_text='Book availability', max_length=1),
        ),
        migrations.AddField(
            model_name='editor',
            name='published_name',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='translator',
            name='published_name',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
